[package]
name = "electrs"
version = "0.4.1"
authors = ["Roman Zeyde <me@romanzey.de>"]
description = "An efficient re-implementation of Viacoin Electrum Server in Rust"
license = "MIT"
homepage = "https://github.com/viacoin/electrs"
repository = "https://github.com/viacoin/electrs"
keywords = ["viacoin", "bitcoin", "electrum", "server", "index", "database"]
documentation = "https://docs.rs/electrs/"
readme = "README.md"
edition = "2018"

[features]
default = []
liquid = ["elements"]

[dependencies]
arraydeque = "0.4"
arrayref = "0.3"
base64 = "0.10"
bincode = "1.0"
bitcoin-bech32 = "0.8"
chan = "0.1"
chan-signal = "0.3"
clap = "2.31"
dirs = "1.0"
error-chain = "0.12"
futures = "0.1"
glob = "0.3"
hex = "0.3"
hyper = "0.12"
itertools = "0.8.0"
libc = "0.2"
log = "0.4"
lru = "0.1"
lru-cache = "0.1.1"
num_cpus = "1.0"
page_size = "0.4"
prometheus = "0.5"
rayon = "1.0"
rocksdb = "0.12"
rust-crypto = "0.2"
secp256k1 = "0.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
stderrlog = "0.4.1"
sysconf = ">=0.3.4"
time = "0.1"
tiny_http = "0.6"
url = "1.0"

[dependencies.viacoin]
version = "0.17"
features = ["serde"]

[dependencies.bitcoin_hashes]
version = "0.3"
features = ["serde"]

[dependencies.elements]
optional = true
git = "https://github.com/ElementsProject/rust-elements/"
rev = "17cd94a09ea0d7f868a3d512484a1ff6147991c4" # from master branch
features = ["serde-feature"] # Doesn't look to work by now

[dev-dependencies]
tempfile = "3.0"

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
